name: Releases
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v0.0.1
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out source code
        uses: actions/checkout@v2
        with:
          path: main
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Tidy
        env:
          GOPROXY: "https://proxy.golang.org"
        run: cd main && go mod tidy && git diff --quiet HEAD

      - name: Build imagestream plugin linux amd64
        env:
          GOPROXY: "https://proxy.golang.org"
        run: cd main/ && GOOS=linux GOARCH=amd64 go build -o ~/main/bin/amd64-linux-imagestreamplugin-${{ github.event.inputs.version }} .

      - name: Build imagestream plugin darwin amd64
        env:
          GOPROXY: "https://proxy.golang.org"
        run: cd main/ && GOOS=darwin GOARCH=amd64 go build -o ~/main/bin/amd64-darwin-imagestreamplugin-${{ github.event.inputs.version }} .

      - name: Build imagestream plugin darwin arm64
        env:
          GOPROXY: "https://proxy.golang.org"
        run: cd main/ && GOOS=darwin GOARCH=arm64 go build -o ~/main/bin/arm64-darwin-imagestreamplugin-${{ github.event.inputs.version }} .

      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "~/main/bin/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}

      - name: Checkout crane-plugins
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/crane-plugins
          token: ${{ secrets.PLUGIN_RELEASE }}

      - name: Updating index file and adding manifest
        run: |
          cat << EOF >> index.yml
          ImagestreamPlugin-${{ github.event.inputs.version }}: https://github.com/${{ github.repository_owner }}/crane-plugins/raw/main/plugins/Imagestream/ImagestreamPlugin-${{ github.event.inputs.version }}.yml
          EOF
          mkdir -p plugins/Imagestream
          cat << EOF >> plugins/Imagestream/ImagestreamPlugin-${{ github.event.inputs.version }}.yml
          name: ImagestreamPlugin
          shortDescription: ImagestreamPlugin
          description: this is ImagestreamPlugin
          version: ${{ github.event.inputs.version }}
          binaries:
            - os: linux
              arch: amd64
              uri: https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.version }}/amd64-linux-imagestreamplugin-${{ github.event.inputs.version }}
            - os: darwin
              arch: amd64
              uri: https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.version }}/amd64-darwin-imagestreamplugin-${{ github.event.inputs.version }}
            - os: darwin
              arch: arm64
              uri: https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.version }}/arm64-darwin-imagestreamplugin-${{ github.event.inputs.version }}
          optionalFields:
            - flagName: "src-internal-registry"
              help:     "Internal registry hostname[:port] used to determine whether an istag references a local image"
              example:  "image-registry.openshift-image-registry.svc:5000"
          EOF

      - name: Create Pull Request against crane-plugins
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PLUGIN_RELEASE }}
          commit-message: Updating index and adding manifest from imagestream plugin release
          title: Adding imagestream plugin from release ${{ github.event.inputs.version }}
          body: Update index and add manifest to include version ${{ github.event.inputs.version }} of imagestream plugin
          branch: ImagestreamPlugin
          base: main
